[all:vars]
ansible_python_interpreter=/usr/bin/python3

# ─── Annuaire & DNS ───
[ipa]
vm_ipa ansible_host=192.168.10.20

# ─── Web & SSO ───
[web]
vm_web ansible_host=192.168.10.30

# ─── Messagerie ───
[mail]
vm_mail ansible_host=192.168.10.40

# ─── Fichiers ───
[files]
vm_files ansible_host=192.168.10.50

# ─── Observabilité ───
[obs]
vm_obs ansible_host=192.168.10.60

# ─── Groupe global (toutes les VMs sauf ansible) ───
[lab:children]
ipa
web
mail
files
obs
